# Generated by Django 5.1.6 on 2025-03-04 22:27

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Estoque',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nome_produto', models.CharField(max_length=255, unique=True)),
                ('quantidade', models.PositiveIntegerField(default=0)),
                ('unidade', models.CharField(choices=[('kg', 'Quilogramas'), ('g', 'Gramas'), ('ton', 'Toneladas'), ('sc', 'Sacos'), ('un', 'Unidades')], default='kg', max_length=10)),
            ],
        ),
    ]
