# Generated by Django 5.1.6 on 2025-03-04 22:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('estoque', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='estoque',
            name='nome_produto',
        ),
        migrations.AddField(
            model_name='estoque',
            name='nome',
            field=models.CharField(default='Desconhecido', max_length=255),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='estoque',
            name='quantidade',
            field=models.PositiveIntegerField(),
        ),
        migrations.AlterField(
            model_name='estoque',
            name='unidade',
            field=models.CharField(choices=[('litros', 'Litros'), ('sacas', 'Sacas'), ('pacotes', 'Pacotes'), ('unidades', 'Unidades'), ('quilos', 'Quilos'), ('garrafas', 'Garrafas')], default='unidades', max_length=10),
        ),
    ]
