# Generated by Django 5.1.6 on 2025-03-04 21:37

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Feira',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('data', models.DateField()),
                ('relatorio', models.TextField(blank=True, null=True)),
                ('valor_faturado', models.DecimalField(decimal_places=2, max_digits=10)),
                ('valor_fiado', models.DecimalField(decimal_places=2, default=0.0, max_digits=10)),
            ],
        ),
    ]
