# Generated by Django 5.1.6 on 2025-03-04 23:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('financeiro', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='despesa',
            name='categoria',
            field=models.CharField(choices=[('Trabalhadores', 'Trabalhadores'), ('Combustível', 'Combustível'), ('Descarregamento', 'Descarregamento'), ('Peças', 'Peças'), ('Serviços', 'Serviços'), ('Tecnologia', 'Tecnologia'), ('Construção', 'Construção')], default='Trabalhadores', max_length=20),
        ),
    ]
