# Generated by Django 5.1.6 on 2025-03-05 04:26

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='CreditoCliente',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nome_devedor', models.CharField(max_length=255)),
                ('valor', models.DecimalField(decimal_places=2, max_digits=10)),
                ('prazo', models.CharField(choices=[('semanal', 'Semanal'), ('15dias', '15 Dias'), ('45dias', '45 Dias')], default='15dias', max_length=10)),
                ('data_registro', models.DateField(auto_now_add=True)),
            ],
        ),
    ]
