# Generated by Django 5.1.6 on 2025-03-05 04:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('credito', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='creditocliente',
            old_name='nome_devedor',
            new_name='nome',
        ),
        migrations.RemoveField(
            model_name='creditocliente',
            name='data_registro',
        ),
        migrations.AddField(
            model_name='creditocliente',
            name='status',
            field=models.CharField(choices=[('por pagar', 'Por Pagar'), ('pago', 'Pago')], default='por pagar', max_length=10),
        ),
        migrations.AlterField(
            model_name='creditocliente',
            name='prazo',
            field=models.CharField(choices=[('semanal', 'Semanal'), ('15dias', '15 dias'), ('45dias', '45 dias')], max_length=10),
        ),
    ]
