# Generated by Django 5.1.6 on 2025-03-05 14:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('credito', '0002_rename_nome_devedor_creditocliente_nome_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='creditocliente',
            name='prazo',
            field=models.CharField(choices=[('semanal', 'Semanal'), ('15_dias', '15 dias'), ('45_dias', '45 dias')], default='semanal', max_length=10),
        ),
    ]
