# Generated by Django 5.1.6 on 2025-03-04 21:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('compras', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='compra',
            name='metodo_pagamento',
            field=models.CharField(choices=[('cheque', 'Cheque'), ('dinheiro', 'Dinheiro'), ('credito', 'Crédito')], default='dinheiro', max_length=10),
        ),
    ]
